### ISSUE TITLE
Could jobmananger service support Nodeport?

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#101]

**Comment by functicons** [comment]
I think it should be feasible, we can add an `AccessScope` type `Node` in the CR. But I'm interested in your use case, does `AccessScope: Cluster` + `kubectl proxy` or `kubectl port-forward` work for you?

**Comment by Mrart** [comment]
I have used kubectl proxy,  It is worked, but I want use it in product env ,we need NodePort ,I think I can merge It, Do we have email List for discuss?

**Comment by functicons** [comment]
Sorry, we don't have a mailing list yet, issues are discussed here. We welcome your contributions!
