### ISSUE TITLE
GCS submit job should use a provided service account

### ISSUE THREAD

**Issue by afilipchik** [GoogleCloudPlatform/flink-on-k8s-operator#102]
Looking at a docker image, it downloads provided jar file from GCP using gsutil and it looks like it is using default permissions of the kube node. 
There should be a way to provide a key instead (as it is possible for task and job managers). 
Can be as simple as:
gcloud auth activate-service-account --key-file=...

**Comment by functicons** [comment]
Thanks for the feedback! We'll add it.

In addition, we just supported init containers for job pod, which could be used for downloading remote job jar, see this [example](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/config/samples/flinkoperator_v1alpha1_remotejobjar.yaml). In this case, you can create a Secret with the service account, mount it into the init container, activate the service account, then download the jar from GCS.

**Comment by functicons** [comment]
Add service account support in https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/112, and updated the doc in https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/113.
