### ISSUE TITLE
Support for namespaced operator

### ISSUE THREAD

**Issue by elanv** [GoogleCloudPlatform/flink-on-k8s-operator#105]
Currently, only one operator can be deployed to a cluster as cluster-scoped. There are use cases that require operators watch only specific namespace. For example, some k8s clusters are not allowed to deploy cluster-scoped Flink operators, so tenants may need a controller restricted to their own namespace. It is also possible that tenants sharing one k8s cluster may want different versions of the operator.

**Comment by functicons** [comment]
Thanks for the feature request, it looks good to me.

**Comment by functicons** [comment]
Seems the requirement includes 2 types of namespaces? One is the namespace in which the operator runs in, the other is the namespace in which users create CRs in and the operator watches for? Is my understanding correct?

**Comment by elanv** [comment]
Yes you are right.  I also noticed those two types.

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/143

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/145
