### ISSUE TITLE
support start from checkpoint

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#106]

**Comment by functicons** [comment]
Could you elaborate?
1) what it means by "start from checkpoint"?
2) What is the use case?
3 Do you have any suggestions on what to add in the CR to support it?

**Comment by Mrart** [comment]
ok ,It means  savepoint, It has supported

**Comment by functicons** [comment]
Okay, thanks for the clarification!
