### ISSUE TITLE
Return status after created;

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#108]
Now I run " kubectl  apply -f config/samples/flinkoperator_v1alpha1_flinkjobcluster.yaml ",It logs "created", and " kubectl  describe -f config/samples/flinkoperator_v1alpha1_flinkjobcluster.yaml " to get task status, So I want 'kubectl  apply -f config/samples/flinkoperator_v1alpha1_flinkjobcluster.yaml' and return the task result.

**Comment by functicons** [comment]
I think this is out of the control of the operator, it is the behavior of `kubectl apply`. The job of `kubectl apply` is to create the resource, then the controller takes care reconciling the observed state towards the desired state.
