### ISSUE TITLE
Job submission failed for akka.pattern.AskTimeoutException

### ISSUE THREAD

**Issue by afilipchik** [GoogleCloudPlatform/flink-on-k8s-operator#109]
I don't think #94 fixed it. Still can see same issue, akka gets a timeout and job restarts. Maybe job should check whether previous submission is still running?

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/104

**Comment by afilipchik** [comment]
That might be a bit aggressive for jobs with a large state. It looks like currently the job will be resubmitted it submission job fails (which can happen if node under it fails). This might trigger an undesirable outage.

**Comment by afilipchik** [comment]
Found: https://issues.apache.org/jira/browse/FLINK-11143

Looks like that is the root cause.

**Comment by afilipchik** [comment]
And disabling checkpointing fixes it (at least in my case)

**Comment by functicons** [comment]
I think #118 could help with this issue.
