### ISSUE TITLE
Back-off restarting failed container, but job status is Pending

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#132]
"status": {
        "components": {
            "configMap": {
                "name": "flinkjobcluster-sample-configmap",
                "state": "Ready"
            },
            "job": {
                "id": "",
                "name": "flinkjobcluster-sample-job",
                "state": "Pending"
            },
            "jobManagerDeployment": {
                "name": "flinkjobcluster-sample-jobmanager",
                "state": "Ready"
            },
            "jobManagerService": {
                "name": "flinkjobcluster-sample-jobmanager",
                "state": "Ready"
            },
            "taskManagerDeployment": {
                "name": "flinkjobcluster-sample-taskmanager",
                "state": "Ready"
            }
        },
        "lastUpdateTime": "2019-11-22T12:19:42Z",
        "state": "Running"
    }
}

"Back-off restarting failed container" error in job container

**Comment by functicons** [comment]
Have your flink operator image synced past https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/123/files? We have disabled restarting failed job at k8s job-level.
