### ISSUE TITLE
Architecture Documentation

### ISSUE THREAD

**Issue by krishnaarava** [GoogleCloudPlatform/flink-on-k8s-operator#133]
Need documentation of the architecture, the different components and their details. Bonus would be to describe how this operator is better than lyft flink operator here https://github.com/lyft/flinkk8soperator

**Comment by Mrart** [comment]
I think we need state machine describe like‘https://github.com/lyft/flinkk8soperator/blob/master/docs/state_machine.md’

**Comment by functicons** [comment]
There is a CNCF Webinar for this operator now: [video](https://www.youtube.com/watch?v=MXj4lo8XHUE), [slides](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/apache-flink-on-kubernetes-operator-20200212.pdf).
