### ISSUE TITLE
Containerize Beam or Flink App and use with connector 

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudPlatform/flink-on-k8s-operator#151]
It will be nice to use docker images instead of `jarFile: ./examples/streaming/WordCount.jar`

So that we can use Beam with Flink on K8s using FlinkOnK8sOperator

**Comment by functicons** [comment]
We'll support Beam on this Flink operator in the near future, stay tuned.

**Comment by functicons** [comment]
Just added a doc on [running Apache Beam Python jobs with the Flink Operator](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/beam_guide.md). We will add Beam python job as a first class job type in the future.

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/174
