### ISSUE TITLE
deploy flink cluster on multiple k8s namespace of k8s cluster

### ISSUE THREAD

**Issue by pzou1974** [GoogleCloudPlatform/flink-on-k8s-operator#153]
We'd like to have multiple k8s namespaces of k8s cluster. each namespace has one Flink cluster.

**Comment by Mrart** [comment]
I think this project support you request. you can control this by your self,but each namespace has one flink cluster is seems not a good idea. If you need do this, just control by yourself.

**Comment by functicons** [comment]
It is a supported feature, run  `make deploy [FLINK_OPERATOR_NAMESPACE=<namespace>]`, see more details at the [user guide](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/user_guide.md). You can also configure the namespace of CRs the operator watches through the `--watch-namespace` commandline flag, see https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/145.

**Comment by pzou1974** [comment]
close the issue
