### ISSUE TITLE
Record savepoint events.

### ISSUE THREAD

**Issue by elanv** [GoogleCloudPlatform/flink-on-k8s-operator#156]
It would be helpful, if savepoint events are recorded.
For example, although savepointing fails, it's difficult to recognize.
Currently, As far as I know, we should look operator logs to find out checkpointing problems.

**Comment by ChethanUK** [comment]
> savepoint events are recorded.

Recorded like pod events?

**Comment by elanv** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/208
