### ISSUE TITLE
v1beta1 chart archive missing

### ISSUE THREAD

**Issue by MihaiAnei** [GoogleCloudPlatform/flink-on-k8s-operator#157]
Even though the v1beta1 version exists here:

https://googlecloudplatform.github.io/flink-on-k8s-operator/index.yaml

the archive is not:

https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/releases/download/flink-operator-v1beta1/flink-operator-v1beta1.tgz

Probably something missing from the latest release :)

**Comment by MihaiAnei** [comment]
This might happen because index.yaml is broken:

https://github.com/helm/helm/issues/2315

**Comment by hongyegong** [comment]
Added. Pleaese check again. @MihaiAnei
