### ISSUE TITLE
require flink-operator without webhook

### ISSUE THREAD

**Issue by pzou1974** [GoogleCloudPlatform/flink-on-k8s-operator#159]
for spark-operator we can pick with or without webhook. We'd like to hava flink-operator without webhook

**Comment by pzou1974** [comment]
there are some option under https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/config/default/kustomization.yaml  but still it looks like code is tightly with webhook Please check bug #160
Need well document it

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/167
