### ISSUE TITLE
namespace delete stuck at after  make undeploy 

### ISSUE THREAD

**Issue by pzou1974** [GoogleCloudPlatform/flink-on-k8s-operator#161]
I manually perform  "kubectl delete ns/[my_name_space] 
it is hanging.

kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n [my-namespace]
error: unable to retrieve the complete list of server APIs: webhook.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request

**Comment by functicons** [comment]
I encountered the problem once and only once as well. Not sure if it is Kubernetes problem or our problem.

**Comment by functicons** [comment]
As a workaround, I think we can update the `make undeploy` leaving the namespace undeleted as it doesn't consume compute/storage resources.

**Comment by pzou1974** [comment]
Yes. I did make undeploy.  but still stuck. namepsace in on terminating status. the problem is our kubernetes framework  added namespace status check cross the k8s cluster and will block the new deployment :(
I suggest if we can document. if failed to delete ns. what are the possible resource associate with it.

**Comment by Mrart** [comment]
I encount the problems as well. because some thing undeleted like certmanager.

**Comment by ChethanUK** [comment]
> namepsace in on terminating status.

Since namespace is stuck in terminating status, Do the following:

1.  Run `kubectl proxy` 

2. Open new terminal:

NS -> namespace which is stuck.

```bash
NS=flink-operator-system
kubectl get namespace $NS -o json >tmp.json
sed 's/"kubernetes"//' tmp.json >tmp1.json
curl -k -H "Content-Type: application/json" -X PUT --data-binary @tmp1.json http://127.0.0.1:8001/api/v1/namespaces/$NS/finalize
```

Now, if you check: `kubectl get namespaces` namespace should be deleted within 5 seconds,

**Comment by Mrart** [comment]
@ChethanUK   I know use your method can resovlf this problems。 but I think we still need find the deep reason， and fixed it!

**Comment by functicons** [comment]
> I encount the problems as well. because some thing undeleted like certmanager.

We have removed the dependency on certmanager.

**Comment by pzou1974** [comment]
when you will release the none certmanager fix?

**Comment by functicons** [comment]
@pzou1974 It is done in https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/167.
