### ISSUE TITLE
HPA for job Cluster 

### ISSUE THREAD

**Issue by pzou1974** [GoogleCloudPlatform/flink-on-k8s-operator#165]
Any possibility for job cluster HPA? 
We can resume from checkpoint.

**Comment by functicons** [comment]
What do you mean by HPA?

**Comment by pzou1974** [comment]
kubernetes Horizontal Pod Autoscaler

**Comment by functicons** [comment]
IIUC, HPA is not supported by Flink yet, but it on the roadmap. This SO [answer](https://stackoverflow.com/questions/58791371/how-do-i-scale-up-down-a-running-flink-cluster) has more details.
