### ISSUE TITLE
Setting metrics reporter host to status.hostIP

### ISSUE THREAD

**Issue by aroch** [GoogleCloudPlatform/flink-on-k8s-operator#166]
Is there a way to set a property in flinkProperties to status.hostIP?

My use-case is to set a metrics reporter for StatsD to send metrics to a sidecar container, so I need access to the host IP:
```
metrics.reporter.dgstsd.host: ${STATSD_AGENT_HOST}
```

In the official Flink Dockerfile you can set a FLINK_PROPERTIES environment variable which can contain values that are environment variables that will get substituted at runtime:

```
    if [ -n "${FLINK_PROPERTIES}" ]; then
        echo "${FLINK_PROPERTIES}" >> "${CONF_FILE}"
    fi
    envsubst < "${CONF_FILE}" > "${CONF_FILE}.tmp" && mv "${CONF_FILE}.tmp" "${CONF_FILE}"
```
The configmap mounted to the flink-conf.yaml is ReadOnly so this will not work.

Is there a way around this?

**Comment by functicons** [comment]
This is a good question, we might need a way to make flink-config.yaml editable.

**Comment by functicons** [comment]
The init container based solution might be what we need: https://serverfault.com/questions/909052/kubernetes-configmap-only-writable-by-root
