### ISSUE TITLE
Why is cert-manager 0.10?

### ISSUE THREAD

**Issue by RohitR1** [GoogleCloudPlatform/flink-on-k8s-operator#172]
Current instruction saying to use 0.10 [cert manager ](
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/tree/master/helm-chart/flink-operator#install-the-dependency-chart---cert-manager)

@hongyegong Will everything work properly with 0.13? 

Also, If I already have ingress how can I create Ingress for each job? Something like 
$ curl https://raw.githubusercontent.com/lyft/flinkk8soperator/v0.4.0/deploy/config.yaml

**Comment by hongyegong** [comment]
cert-manager has been removed from flink operator. Please pull from the head and deploy flink operator again.
