### ISSUE TITLE
Why only taskmananger suppported sidecars?

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#176]
Why I want use sidecar collect logs, the jobmanang not supported sidecars.

**Comment by functicons** [comment]
Because there are no known use cases for sidecars with JM. We can add it if you have specific use cases, and we'd like to hear more details.

**Comment by functicons** [comment]
{{{{{{{{{[[[[[[[[[[[[[["??????;///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////]

**Comment by Mrart** [comment]
Use filebeat collect jobmanager logs. I think I can do it. and in our product env, We need this function.

**Comment by Mrart** [comment]
Ok, I have implement in our env, I will fixed this issue.

**Comment by iamsudip** [comment]
@functicons One more usecase: flink application running as `flink:flink` and if we attach persistent volumes to both taskmanagers and jobmanagers, we can't write to them. So we need an init container which will chown flink:flink /directory

**Comment by functicons** [comment]
@iamsudip are you talking about init container or sidecar container?

**Comment by sudip-moengage** [comment]
@functicons I'm talking about initcontainer. I went trough CRD doc again and I mistakenly read sidecars instead of initContainers earlier. So, it is supported. Thanks for clarifying.

**Comment by Mrart** [comment]
@functicons  Do you think sidecars is needed?

**Comment by functicons** [comment]
@Mrart since we have use cases for sidecars with JM, we can add it.

**Comment by functicons** [comment]
#186
