### ISSUE TITLE
How to expose prometheus port in jobs?

### ISSUE THREAD

**Issue by iamsudip** [GoogleCloudPlatform/flink-on-k8s-operator#178]
We use prometheus to scrape metrics, the client expose metrics on task-manager-pod:9249/metrics, but the CRD doesn't support other than data, rpc, query ports. Can you suggest a workaround?

**Comment by functicons** [comment]
We discussed this previously https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/114

**Comment by sudip-moengage** [comment]
@functicons Closing. Apologise for not searching enough.
