### ISSUE TITLE
Support for nodeSelector for jobManager and taskManager

### ISSUE THREAD

**Issue by iamsudip** [GoogleCloudPlatform/flink-on-k8s-operator#179]

**Comment by Mrart** [comment]
Is jobManager supported nodeselector？

**Comment by functicons** [comment]
Before we add nodeSelector for JM and TM, the recommended way is to deploy the cluster in a custom namespace, and add nodeSelector to the namespace, see https://stackoverflow.com/questions/52487333/how-to-assign-a-namespace-to-certain-nodes

**Comment by iamsudip** [comment]
@functicons We use AWS EKS, since it's a managed kubernetes master setup, we don't have control to enable PodNodSelector. We can have a mutation webhook but that's more work.

**Comment by functicons** [comment]
@iamsudip Actually, we already supported NodeSelector for JM and TM, it is just missed in the CRD doc. I'll fix the doc. Thanks for the feedback!

**Comment by functicons** [comment]
The doc has been fixed in https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/186
