### ISSUE TITLE
How to update flink-operator online?

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#180]
When we use 'make undeploy and then make deploy', It can update code, but It will delete the exsit 'flinkclusters'. It is dangerous for product env. And how to deploy the operator code online?

**Comment by functicons** [comment]
To upgrade the Flink Operator, the recommended way is to: 1) take a savepoint; 2) delete the existing Flink cluster CRs; 3) run `make undeploy` to delete the operator and the CRD; 4) build new operator then run `make deploy` to redeploy.

**Comment by Mrart** [comment]
It seem can't operate at product env . if many job started . It will take too many times. and the users will not glad about stop the jobs.

**Comment by functicons** [comment]
We have a pending feature request, which proposes to support updating the operator image https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/65.

Maybe we can give it a higher priority.

**Comment by Mrart** [comment]
Thks, We have more then 10,000 flink jobs. Like stop jobs when update operators, It will a very heavy jobs. So This feature is a higher priority

**Comment by Mrart** [comment]
@function, I have push other features ,I have impl. Can you help me to fixed this problem? I think I can't do it with ability.

**Comment by functicons** [comment]
Sorry, I misunderstood the problem. #65 is about updating FlinkCluster CR, instead of the operator itself. Because the operator runs as a k8s Deployment, if you only update the operator image, the update is easy, you simply apply a new YAML. (Don't use `make undeploy` and `make deploy`)

**Comment by Mrart** [comment]
@functicons  Ok，If i update the operator image by update the k8s deployment. The exsit flinkclusters can  be control by the new operator image pods? the the operator code can be update?

**Comment by functicons** [comment]
Correct.

**Comment by Mrart** [comment]
> Correct.

Ok, I will try again, I think  #65  is the other problem. I only want update the controller code of the operator? like that the if I fixed #184 , The new flinkclusters can work with sidecars with jobmananger. but I think #65 is a very import feature。

**Comment by Mrart** [comment]
OK， I think It will have The other problem? the exist flinkcluster can be mananged,When update the deployment ?

**Comment by functicons** [comment]
Yes, updating the operator shouldn't affect existing Flink clusters or jobs. It is because of the reconciliation loop in the operator, it always checks the current status the compare it to the desired state.

**Comment by Mrart** [comment]
kubectl -n flink-operator-system delete -f config/manager/manager.yaml, It show me logs: 
`Error from server (NotFound): error when deleting "config/manager/manager.yaml": namespaces "system" not found
the namespace from the provided object "system" does not match the namespace "flink-operator-system". You must pass '--namespace=system' to perform this operation.
`
So it need #65  to fixed this problems？

**Comment by functicons** [comment]
No, we should not use `delete` here, instead we should just run `make operator-image push-operator-image deploy IMG=<uri>` which builds and pushes the image, then updates the operators.

**Comment by Mrart** [comment]
I have test it, It is running ok. I will add `make update `to makefile.
