### ISSUE TITLE
Add State example with RocksDB and GCS level

### ISSUE THREAD

**Issue by RohitR1** [GoogleCloudPlatform/flink-on-k8s-operator#193]
It will be nice to have an example with RocksDB and GCS

**Comment by functicons** [comment]
I don't quite understand the request, could you elaborate?

**Comment by RohitR1** [comment]
Can we get some flink example of stateful jobs?

This is stateless jobs right..
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/kafka_test_guide.md#3-run-streaming-application-with-the-operator
