### ISSUE TITLE
Helm chart in the incubator repository

### ISSUE THREAD

**Issue by laughingman7743** [GoogleCloudPlatform/flink-on-k8s-operator#202]
Are you planning to register Helm chart in the incubator repository?
A similar project [spark-on-k8s-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator) is registered in the incubator repository.
https://github.com/helm/charts/tree/master/incubator/sparkoperator

I want to register the Helm chart of this project in the incubator repository.

**Comment by hongyegong** [comment]
Hello, please see this - https://github.com/helm/charts#deprecation-timeline

The incubator repo will be deprecated by helm so we will not host flink-operator there.
