### ISSUE TITLE
Move imperative fields to annotations

### ISSUE THREAD

**Issue by elanv** [GoogleCloudPlatform/flink-on-k8s-operator#204]
As far as I know, the kubernetes resource is basically idempotent, therefore the same spec always guarantees the same deployment, and for this, the spec of kubernetes resources is modeled declaratively.

Of course, I think some flexibility should be allowed when defining more complex CRDs than kubernetes resources. However, while implementing update/rollback feature which deployment consistency is important, I found that some fields that is imperative rather than declarative complicate the problem somewhat.  These fields are cancelRequested and savepointGeneration of job.spec. I would like to suggest moving these fields to annotations. I think this is helpful not only for the update/rollback feature, but also for improving the specification.

**Comment by functicons** [comment]
I agree, modeling cancelRequested an savepointGeneration as annotations would be better, but I'm not sure if there are unexpected side effects, so be careful when making the change.

**Comment by elanv** [comment]
Ok, thanks. I will attempt this.

**Comment by elanv** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/208
