### ISSUE TITLE
How to use deployments/deploy.sh?

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#205]
@functicons  When I use deployments/deploy.sh, it can logs 
"E0327 11:28:07.163778       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:flink-operator:default" cannot list resource "deployments" in API group "apps" at the cluster scope
E0327 11:28:08.162272       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.FlinkCluster: flinkclusters.flinkoperator.k8s.io is forbidden: User "system:serviceaccount:flink-operator:default" cannot list resource "flinkclusters" in API group "flinkoperator.k8s.io" at the cluster scope
E0327 11:28:08.162933       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:flink-operator:default" cannot list resource "services" in API group "" at the cluster scope
E0327 11:28:08.163850       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:flink-operator:default" cannot list resource "jobs" in API group "batch" at the cluster scope
E0327 11:28:08.164978       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:flink-operator:default" cannot list resource "deployments" in API group "apps" at the cluster scope
"

**Comment by functicons** [comment]
The script is obsolete, it is not documented and should be deleted.

**Comment by Mrart** [comment]
But，I think I need this method to deploy，because We don't want install kustomise tool on deploy server。

**Comment by functicons** [comment]
Kustomize is no longer needed, we require kubectl v1.14+ which has Kustomize built in.

**Comment by Mrart** [comment]
@functicons  ok, I think i need do this in our product env. because we don't want update kubectl and don't want use Kustomize. I think it is bad request,but I need do it.

**Comment by functicons** [comment]
If that is what you need, I think you can break it down into 2 steps: first, in your dev env, use kubectl v1.14+ to generate the YAML from the templates; then in your prod env, use kubectl (v1.14-) to apply the YAML to the cluster.
