### ISSUE TITLE
Error: metadata.managedFields.fieldsType

### ISSUE THREAD

**Issue by rafiwicht** [GoogleCloudPlatform/flink-on-k8s-operator#206]
Hello everyone

When I try to apply any FlinkCluster Resource, I get an Error:
`The FlinkCluster "flinkjobcluster-sample" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be 'FieldsV1'`

Kubernetes Version: 1.18.0

I saw they changed the [Server Side Apply](https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply). That could be the problem. I'm currently downgrading to find out if it solves the problem.

Best regards,

Rafael

**Comment by rafiwicht** [comment]
It looks like it is working with Kubernetes Version 1.17.4.

**Comment by rafiwicht** [comment]
Kubernetes vresion 1.17.4 works.

**Comment by elanv** [comment]
I think it was resolved via #247 .

**Comment by Enzo90910** [comment]
I still have this although I used the last master commit.
