### ISSUE TITLE
doesn't work in k8s1.18: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`

### ISSUE THREAD

**Issue by kinderyj** [GoogleCloudPlatform/flink-on-k8s-operator#210]
my k8s cluster is a minikube with version k8s 1.18,
I installed the flink operator and then try to run:
kubectl apply -f config/samples/flinkoperator_v1beta1_flinksessioncluster.yaml
got the following error:
The FlinkCluster "flinksessioncluster-sample" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`
How can this error be fixed?

the flink operator's resouce works well:
kubectl get all
NAME                                                     READY   STATUS    RESTARTS   AGE
pod/flink-operator-controller-manager-64f697fb86-k2r9q   2/2     Running   0          26s

NAME                                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/flink-operator-controller-manager-metrics-service   ClusterIP   10.111.89.19     <none>        8443/TCP   26s
service/flink-operator-webhook-service                      ClusterIP   10.109.152.186   <none>        443/TCP    26s
service/kubernetes                                          ClusterIP   10.96.0.1        <none>        443/TCP    4d8h

NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/flink-operator-controller-manager   1/1     1            1           26s

NAME                                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/flink-operator-controller-manager-64f697fb86   1         1         1       26s

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by functicons** [comment]
Thanks for the feedback, will fix!

**Comment by elanv** [comment]
I think it was resolved through #247 .
