### ISSUE TITLE
The job state shows succeeded while the job actually failed

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#218]
When we user the submit.sh to submit job ,and the job submited failed. We have change the job.state to "Succeeded", but the job pod log is "notebook_27222_test_memcache_v20200408 (FAILED)".

**Comment by Mrart** [comment]
I think we have lost, check change the status after the job pod stops.

**Comment by Mrart** [comment]
I have run in product env，I think this is a very serious bug.

**Comment by Mrart** [comment]
@functicons , Can you help me fixed this.

**Comment by functicons** [comment]
Is there a way to reproduce the problem?

**Comment by functicons** [comment]
I think the problem is that, the [submit-job.sh](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/controllers/flinkcluster_submit_job_script.go#L69) didn't distinguish `FINISHED` with `FAILED`, they both exit with 0. The fix is when `FAILED` or `CANCELED`, exit with 1.

**Comment by functicons** [comment]
I reproduced this problem by deliberately changing the `--input` of the sample job cluster to a non-existent file `README.txtxxx`.

The job completed successfully (which is a false positive):

```
$ kubectl get jobs

NAMESPACE   NAME                         COMPLETIONS   DURATION   AGE
default     flinkjobcluster-sample-job   1/1           50s        3m23s
```

but in the Pod log we see it actually failed:

```
$ klogs flinkjobcluster-sample-job-lc5sw
...
Submitting job...
/opt/flink/bin/flink run --jobmanager flinkjobcluster-sample-jobmanager:8081 --class org.apache.flink.streaming.examples.wordcount.WordCount --parallelism 2 --detached ./examples/streaming/WordCount.jar --input ./README.txtxxx
Starting execution of program
Printing result to stdout. Use --output to specify output path.
Job has been submitted with JobID b90ec01e7daf08151e0fc3e5066b506e

Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
09.04.2020 17:21:44 : b90ec01e7daf08151e0fc3e5066b506e : Streaming WordCount (RUNNING)
--------------------------------------------------------------
No scheduled jobs.

Waiting for job to finish...
Waiting for response...
No running jobs.
No scheduled jobs.
---------------------- Terminated Jobs -----------------------
09.04.2020 17:21:44 : b90ec01e7daf08151e0fc3e5066b506e : Streaming WordCount (FAILED)
--------------------------------------------------------------
09.04.2020 17:21:44 : b90ec01e7daf08151e0fc3e5066b506e : Streaming WordCount (FAILED)

Job has terminated, exiting...
```
