### ISSUE TITLE
chart installed failed in flink-operator-v1beta1

### ISSUE THREAD

**Issue by kinderyj** [GoogleCloudPlatform/flink-on-k8s-operator#221]
version: flink-operator-v1beta1
I try to  install the flinkoperator with helm3 and get the following errors:

helm3 install flinkoperator ./flink-operator/
Error: parse error at (flink-operator/templates/flink-operator.yaml:2756): undefined variable "$clusterName"

I changed the $clusterName to "clusterName" mananly and tried anagin:
helm3 install flinkoperator ./flink-operator/
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1", unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"]

**Comment by hongyegong** [comment]
Please try helm install with [instruction](helm repo add flink-operator-repo https://googlecloudplatform.github.io/flink-on-k8s-operator/) again. Just update with new release hosted by helm server.

**Comment by kinderyj** [comment]
It works now, thanks.
