### ISSUE TITLE
Failed to download "flink-operator/flink-operator"

### ISSUE THREAD

**Issue by kinderyj** [GoogleCloudPlatform/flink-on-k8s-operator#225]
According to the Readme in flink-on-k8s-operator/helm-chart/flink-operator/ of the master branch,
I try to install the operator from the chart.
But I get the follow message both in helm2 and helm3:

helm repo add flink-operator-repo https://googlecloudplatform.github.io/flink-on-k8s-operator/
helm install  flink-operator-repo/flink-operator  test-name

Error: failed to download "flink-operator/flink-operator"

**Comment by xuebingli** [comment]
I'm having the same issue with `helm install`
```
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

$ helm search repo flink-operator-repo
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION
flink-operator-repo/flink-operator	v1beta1      	1.0        	A Helm chart for flink on Kubernetes operator

$ helm install flink-operator flink-operator-repo/flink-operator --set operatorImage.name=gcr.io/flink-operator/flink-operator:latest
Error: failed to download "flink-operator-repo/flink-operator" (hint: running `helm repo update` may help)
```
`helm repo update` does not help. 

Happy to provide more details if needed.

**Comment by xuebingli** [comment]
It works for me now. @kinderyj you probably want to try again.

**Comment by kinderyj** [comment]
New version released. It also works for me. Closed.
