### ISSUE TITLE
Expose additional ports of JM/TM pods does not work

### ISSUE THREAD

**Issue by yalctay93** [GoogleCloudPlatform/flink-on-k8s-operator#264]
Expose additional ports of JM/TM pods #241

Is not working. I have deployed the following example: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/examples/prometheus/flink_metric_cluster.yaml

however, if you use kubectl get pod <jobmanager_pod_name> -oyaml

then the extraPorts added are not visible. How is that so? My pod-monitor is not showing me any scrapes on prometheus. Could this be the issue? Shouldnt the extraPort be visible when using k get pods -oyaml command?

Anyone was able to get this working? Thanks!

The pod-monitor that I am using is this:
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-pod-monitor
  labels:
    prometheus: cluster-metrics
spec:
  podTargetLabels:
    - cluster
    - component
  selector:
    matchLabels:
      app: flink
  podMetricsEndpoints:
  - port: prom

I can see the pod-monitor in the prometheus targets, however it was 0 targets up

**Comment by functicons** [comment]
The feature is added recently, which operator image are you using?

**Comment by yalctay93** [comment]
> The feature is added recently, which operator image are you using?

flink-operator:v1beta1-1 <-- I might try another version.. which one has been confirmed to work with the extraPorts configuration?

**Comment by functicons** [comment]
We just released a new image `gcr.io/flink-operator/flink-operator:v1beta1-5` today with some bug fixes, I recommend you to use that one. Thanks!

```
$ gcloud container images list-tags gcr.io/flink-operator/flink-operator
DIGEST        TAGS              TIMESTAMP
fd430a5427bf  v1beta1-5         2020-06-09T11:01:06
4acfc1fac571  latest,v1beta1-4  2020-05-18T10:35:44
023148f9794e  v1beta1-3         2020-04-09T21:26:07
794f9bb94cf2                    2020-03-25T12:19:26
65f2807c57a2  v1beta1-2         2020-03-23T16:59:53
67a4bafd927f  v1beta1-1         2020-01-08T18:22:11
6ecaab909355  v1beta1           2020-01-08T13:52:28
ad0f16090f0b  v1alpha1          2020-01-03T15:35:32
```

**Comment by yalctay93** [comment]
the v1beta1-5 tag did the job. thanks alot!
