### ISSUE TITLE
How to set service account for flink CRD?

### ISSUE THREAD

**Issue by technomage** [GoogleCloudPlatform/flink-on-k8s-operator#272]
Is there a way to specify the service account a flink job/cluster will use when run?  I do not see such in the CRD spec, but would like the option to specify the service account and thus the RBAC access the job has to the rest of the cluster.

**Comment by functicons** [comment]
Current, the job always uses the default service account of the FlinkCluster's namespace. But we are open to add the support of custom service account.

**Comment by technomage** [comment]
So I need to create a "default" service account in the namespace the CRD is created within?  I can live with that for now.  Thanks.

**Comment by functicons** [comment]
You don't need to create the default service account, every namespace comes with one. See this [doc](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-multiple-service-accounts) for more details.
