### ISSUE TITLE
flink jobManager and taskManager annotations not configureable

### ISSUE THREAD

**Issue by yalctay93** [GoogleCloudPlatform/flink-on-k8s-operator#275]
In our setup we use fluent-bit to parse log output in the correct format for us. We created parsers for both jobManager and taskManager logs and would now like to use the annotations field, to make use of them:

annotations:
  fluentbit.io/parser: flink-job_task_manager

apparently the operator does not create the annotations field when deploying the jobManager and taskManager. Is there a way to do it?

**Comment by yalctay93** [comment]
I have seen a commit that apparently enables the above problem https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/commit/04353c8a4b924d7cb5717e231edd3bcbdbda02a8

However, the operator image has not been renewed according to the registry. The latest one is v1beta1-5 and 16 days old: https://console.cloud.google.com/gcr/images/flink-operator/GLOBAL/flink-operator

**Comment by functicons** [comment]
We'll release a new version of the operator image next week. Before that, you can follow the [developer guide](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/developer_guide.md) and build your own image if needed.

**Comment by functicons** [comment]
We just released `gcr.io/flink-operator/flink-operator:v1beta1-6`. The tag `gcr.io/flink-operator/flink-operator:latest` now points to it.
