### ISSUE TITLE
Require dockerfile  example of python beam flink 

### ISSUE THREAD

**Issue by pzou1974** [GoogleCloudPlatform/flink-on-k8s-operator#281]
we'd like to have example of python beam dockerfiles

**Comment by functicons** [comment]
Do you mean Beam job dockerfile? like the `apachebeam/python3.7_sdk:2.18.0` in the [example](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/examples/beam/without_job_server/beam_wordcount_py.yaml#L13)?

**Comment by pzou1974** [comment]
you can close it I figured it out via use apachebeam/python3.7_sdk:2.18.0 s base image
