### ISSUE TITLE
How to specify imagePullSecrets for sidecar containers in cluster definition yaml?

### ISSUE THREAD

**Issue by vp999** [GoogleCloudPlatform/flink-on-k8s-operator#295]
I am trying to download the beam images (e.g.  apachebeam/python3.7_sdk:2.18.0)  from private registry (like ACR).  
This requires "authentication token" for connecting to registry. I could find attribute imagePullSecrets in job definition yaml.  However such attribute is not available for  beam_flink_cluster.yaml.

I am following steps in https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/beam_guide.md  (section : without job server).

**Comment by functicons** [comment]
The attribute `imagePullSecrets` is available for `FlinkCluster`, it is just the example beam_flink_cluster.yaml didn't use it. See the [CRD doc](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/crd.md):

```
FlinkCluster
|__ spec
    |__ image
        |__ name
        |__ pullPolicy
        |__ pullSecrets
```

**Comment by vp999** [comment]
Thank you, 

The "spec" I believe is for flink cluster image (like  flink:1.8.1)
I was checking for side care image (see the screenshot)


also what purpose sidecar serve in cluster definition ?  isnt the sidecar required only for performing  beam  job ?and hence should only be required for job definition ?

![image](https://user-images.githubusercontent.com/31272095/89407721-e9476000-d73c-11ea-8d7d-a9476ef59032.png)

**Comment by functicons** [comment]
The type of sidecar is `corev1.Container`, see https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/52f06dd0c2298dd109151d2037412b76a5208592/api/v1beta1/flinkcluster_types.go#L287, so it supports `imagePullSecrets` just as you define containers for a Pod.

When using Flink as the runner, Beam needs to run a Beam Python worker with each TaskManager, which is used to execute the user-defined python functions. This operator implements it as a sidecar of TM.

**Comment by vp999** [comment]
thank you for your help
