### ISSUE TITLE
Input and output folder path while submitting the jobs

### ISSUE THREAD

**Issue by vp999** [GoogleCloudPlatform/flink-on-k8s-operator#296]
I am trying to setup the beam job using following yaml 
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/examples/beam/without_job_server/beam_wordcount_py.yaml

The yaml requires input and output parameters to be passed.  Are these the local folders on the master node of K8s?
I could see the job executed successfullly but the /tmp/output folder on master node is empty. 

![image](https://user-images.githubusercontent.com/31272095/89269312-5ed90080-d657-11ea-965d-2cb08cd1f6ee.png)

**Comment by functicons** [comment]
The default container filesystem is an ephemeral layer above the container image, whose lifecycle is the same as the container. So the input file is from the image, and the output is local to the container. You need to attach a volume of type `hostPath` if you want it to be from the host node, see https://kubernetes.io/docs/concepts/storage/volumes/#hostpath.

**Comment by vp999** [comment]
Thank you .
Rookie mistake 😀
