### ISSUE TITLE
Use of flink/kubernetes to replace etl jobs (on ssis) : one flink cluster per jobtype or create and destroy flink cluster per job execution

### ISSUE THREAD

**Issue by vp999** [GoogleCloudPlatform/flink-on-k8s-operator#306]
I am trying to see feasibility of replacing the hundreds of feed file ETL jobs created using SSIS packages with apache flink jobs (and kuberentes as underlying infra). One recommendation i saw in some article is "to use one flink cluster for one type of job".

Since i have handful jobs per day of each job type, then this means the best way for me is to create flinkcluster on the fly when executing the job and destroy it to free up resources, is that correct way to do it? I am setting up flinkcluster without job manager.

Any suggestions on best practices for using flink for batch ETL activities.

May be most important question: is flink correct solution for the problem statement or should i go more into Talend and other classic ETL tools?

**Comment by functicons** [comment]
I think ephemeral job clusters (create one cluster for one job, delete the cluster after it finishes) are definitely common for ETL workloads. Here are some scenarios that you might want to use one session cluster to run multiple jobs: 1) you care about cluster set up time and want to avoid overhead of a few minutes for each cluster; 2) you care about resource utilization, want to share Flink JM/TM resources for multiple small jobs.

I would go for job clusters by default as it is much easier to manage.

**Comment by vp999** [comment]
Thank you. this helps.

**Comment by vp999** [comment]
One more question on this . Is there a way to combine cluster creation and job execution together ? This eliminates the need for scripting the dynamic clusterids and port in the yaml .

**Comment by functicons** [comment]
I don't quite understand your question. I think Flink job cluster is already what you need, it is one cluster per job.
