### ISSUE TITLE
Helm Release

### ISSUE THREAD

**Issue by stevehipwell** [GoogleCloudPlatform/flink-on-k8s-operator#314]
It'd be good to get a new _Helm_ release as the code on master works but the _0.1.1_ chart doesn't. You might also want to look at the chart versioning as _v1beta1_ is currently showing up as the latest release (sorting issue I assume).

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/releases/tag/flink-operator-0.2.0 is just released. Let me know if you have any issue, thanks!

**Comment by stevehipwell** [comment]
@functicons it looks like the _Helm_ repo hasn't been updated with this release?

**Comment by zifeo** [comment]
@functicons the helm repo is still on 0.1.1, could you update it?
