### ISSUE TITLE
How cancelRequested to stop and start job and to resume from lastSavepoint can be set?

### ISSUE THREAD

**Issue by guruprasathT** [GoogleCloudPlatform/flink-on-k8s-operator#316]
Hello

I could use `cancelRequested` to stop the job. However to start the job from the lastSavepoint (from autoSavepoint) and then i faced the below validation error. Is there a alternate way to do stop and start the flink-job-cluster job?  

```
upgrade.go:367: [debug] warning: Upgrade "test-job-cluster" failed: cannot patch "test-job" with kind FlinkCluster: admission webhook "vflinkcluster.flinkoperator.k8s.io" denied the request: updating cancelRequested from true to false is not allowed
```

**Comment by elanv** [comment]
It is not allowed to change the field `cancelRequested` from `true` to `false`. 
Alternatively you can stop your job by attaching annotation like:
```
kubectl annotate flinkclusters <CLUSTER-NAME> flinkclusters.flinkoperator.k8s.io/user-control=job-cancel
```
Next, if the job is stopped, it can be restarted by updaing `fromSavepoint`

note: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/user_guide.md#cancel-running-flink-job

**Comment by guruprasathT** [comment]
@elanv 

Thanks for the input. Yes it did work. I understood by spec to resume the cancelled job from the last savepoint we should set  `fromSavepoint` explicitly to restart the job (Initially I mistook it will be resumed from the flinkCluster last generated-Id when the job was cancelled).
