### ISSUE TITLE
Operator chart should consider deployment into existing namespaces

### ISSUE THREAD

**Issue by yaron-idan** [GoogleCloudPlatform/flink-on-k8s-operator#347]
I'm trying to deploy the flink operator into an existing namespace within the cluster using the helm chart in this repository. Since it currently doesn't allow to skip namespace creation, I end up with a collision between the namespace I've already created and the one defined by the template.

WDYT about adding a flag allowing to skip namespace creation? I can create the PR if this feels like a valuable contribution.

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/348
