### ISSUE TITLE
Improve Flink job status tracking

### ISSUE THREAD

**Issue by elanv** [GoogleCloudPlatform/flink-on-k8s-operator#349]
We determine the status of the Flink job via wait_for_job loop in the job submitter.
After job submission, the job pod is still alive for tracking job status.
When I measured resource usage of job pod, each job pod seems to use 200m CPU approximately.
Considering the function, it seems that the resource usage is not small.
It would be nice if it could be improved in a more efficient way.

**Comment by functicons** [comment]
Do you have any idea about what could be improved?

**Comment by elanv** [comment]
We determine the status of the Flink job via wait_for_job loop inside the job submitter pod.
However, we call Flink REST API in each reconcile loop to get Flink job ID already.
What do you think about tracking the Flink job status in reconcile loop via REST API,
and making the job submitter pod to be finished after job submit command executed?

**Comment by elanv** [comment]
And please review this comment as well. 

https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/294#issuecomment-709815077

**Comment by functicons** [comment]
Thanks for your ideas! Let's discuss it in #294.
