### ISSUE TITLE
Use Update instead of deleting component When updating a flinkcluster

### ISSUE THREAD

**Issue by DeliangFan** [GoogleCloudPlatform/flink-on-k8s-operator#360]
When update the flinkcluster spec, the operator will delete all of the old components and create the new components. 

For a session flink cluster, it's a common use case to adjust the task manager replicas, and the deleting old components may result in some bad impacts for a realtime serving.

I'm also wondering why the operator must delete all of the old components rather than apply update actions.

**Comment by elanv** [comment]
There were plans to improve update feature allowing to choose recreating or updating deployment resources. I still have the plan but don't have enough bandwidth to do it right now, so if someone can improve it, that would be good, too.

On the one hand, it seems necessary to introduce native Kubernetes support from Flink 1.10 or later. Flink native kubernetes support feature enables that dynamically manages the task manager according to the resources allocated to the submitted job.

**Comment by DeliangFan** [comment]
> There were plans to improve update feature allowing to choose recreating or updating deployment resources. I still have the plan but don't have enough bandwidth to do it right now, so if someone can improve it, that would be good too.
> 
> On the one hand, it seems necessary to introduce native Kubernetes support feature from Flink 1.10 or later. Flink native kubernetes support feature enables that dynamically manages cluster size according to the resources allocated to the submitted job.

Would you please share your plans. I'm doing the improvement for private cluster, and I would like to make a little contribution to our community.

**Comment by elanv** [comment]
The plan is not detailed enough to share. In my opinion, if you have any good ideas or work in progress, it would be nice to share them here.
