### ISSUE TITLE
Latest release 0.2.0 missing in googlecloudplatform.github.io repo

### ISSUE THREAD

**Issue by nickelozz** [GoogleCloudPlatform/flink-on-k8s-operator#369]
As evidenced [here](https://googlecloudplatform.github.io/flink-on-k8s-operator/index.yaml), the 0.2.0 release is missing in the official repo.

Any chance someone can take a look and publish the latest release? We're currently trying to install the Flink operator as a chart dependency in our project and it's unnecessarily complicated to pull this repo and perform a make deploy separately.

Thanks.

**Comment by functicons** [comment]
@hongyegong could you take a look?

**Comment by ckdarby** [comment]
@functicons With the new image release can you poke @hongyegong to release the new chart, please?

**Comment by functicons** [comment]
Will do, thanks for the reminder.

**Comment by mdolinin** [comment]
@functicons @hongyegong Do you plan to release new chart 0.2.0 here https://googlecloudplatform.github.io/flink-on-k8s-operator/index.yaml? Or maybe it will be new repo?
