### ISSUE TITLE
ConfigMap and Secret fails to mount while deploying Flink Job Cluster

### ISSUE THREAD

**Issue by sugam72** [GoogleCloudPlatform/flink-on-k8s-operator#373]
I am trying to run Flink job cluster with savepoints using gcs connector.
I am following [this](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/images/flink/README.md) document.

When I create the Flink cluster, I get the following error in job manage's event.
`MountVolume.SetUp failed for volume "hadoop-config-volume" : couldn't propagate object cache: timed out waiting for the condition`
`MountVolume.SetUp failed for volume "gcp-service-account-volume" : couldn't propagate object cache: timed out waiting for the condition`

Is there any other consideration I need to take care of apart from the ones mentioned in document mentioned above?

Job cluster runs perfectly fine without hadoopConfig and gcpConfig in yaml, but I want to use the failover mechanism.

**Comment by functicons** [comment]
Can you print the information about `hadoop-config-volume` and `gcp-service-account-volume`, to check if they are in good state?

**Comment by sugam72** [comment]
I am a little new to this. Can you help me understand how can I `describe` these volumes when the container has not created? Or you are asking something else?

**Comment by sugam72** [comment]
Figured this issue comes if secret and configmap are not in the same namespace.
It would be helpful if this consideration can be added to the [documentation](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/tree/master/images/flink)
