### ISSUE TITLE
Support external clusterRef

### ISSUE THREAD

**Issue by regadas** [GoogleCloudPlatform/flink-on-k8s-operator#387]
Hello 👋 !

Was the support of external cluster references discussed at some point? I think I saw an issue here at some point but I can't find it.

The main idea here would be to allow Flink cluster deployments on a separate cluster.

Thanks!

/cc @functicons

**Comment by functicons** [comment]
Do you mean the operator and the flink cluster in 2 clusters?

**Comment by regadas** [comment]
Sorry @functicons this was a really wild idea and it's not really relevant anymore.
