### ISSUE TITLE
Kubernete cluster created by minikube cannot pull image from Google Container Registry

### ISSUE THREAD

**Issue by hongyegong** [GoogleCloudPlatform/flink-on-k8s-operator#40]
When following the developer guide, I created cluster using Minikube and registered image on GCR, then I ran into this problem where pod status will always be ImagePullbackError. This is the current limitation and it should work to create cluster with GKE.

**Comment by functicons** [comment]
Minikube requires service account to be configured to access GCR, see https://ryaneschinger.com/blog/using-google-container-registry-gcr-with-minikube/
