### ISSUE TITLE
Generated pods have an invalid metadata.labels

### ISSUE THREAD

**Issue by syucream** [GoogleCloudPlatform/flink-on-k8s-operator#402]
I recently applied the update feature https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/245 then got such an error:
> Pod “xxx-jobmanager-0” is invalid: metadata.labels: Invalid value: “xxx-jobmanager-755997f66b”: must be no more than 63 characters

It seems to be caused by `controller-revision-hash=xxx-jobmanager-6588f8cbcb` label of a pod. Any good resolution, for e.g. changing the label name, just disabling the update feature for now? Or don't I have any workaround aside from making the name shorter?

**Comment by syucream** [comment]
Or any chance to change logic which generate the label?

**Comment by elanv** [comment]
In “xxx-jobmanager-755997f66b”, the prefix "xxx" is the name of FlinkCluster. The name seems to be quite long. As a workaround, once possible, it would be better to reduce the name of FlinkCluster.

**Comment by syucream** [comment]
That should be the easiest workaround. For a long term, can we get another good way? I feel `-jobmanager-755997f66b` suffix part is also long.

**Comment by syucream** [comment]
I found the same issue https://github.com/kubernetes/kubernetes/issues/79337

**Comment by syucream** [comment]
That should be a known issue which we don't have any other reasonable resolution ... I will just shorten my cluster name. Thanks.
