### ISSUE TITLE
Upgrade streaming job cluster or session cluster

### ISSUE THREAD

**Issue by elanv** [GoogleCloudPlatform/flink-on-k8s-operator#65]
Currently, to upgrade a streaming job cluster or session cluster, you must delete the existing job or cluster and then create a new CR. In this case, the order is as follows.

1. Manually cancel with savepoint using Flink API
2. Delete the current flinkcluster CR
3. Locate the saved savepoint.
4. Create a new CR specifying the manually created savepoint

If the operator can automate the upgrade, it will automate the process.

Considerations by upgrade types:

- Flink image upgrade
  - If the Flink version or java version changes.
  - In this case, tear the existing cluster and re-deploy it with a new image.
- Job only upgrade
  - Restart job by replacing jar or job resources
  - In the same way as upgrading the cluster image, you can delete the cluster and deploy a new one. 
  - Alternatively, you can leave the existing cluster as is and replace only the job and resubmit it to the existing cluster. If you want to apply task-local recovery feature, you may want the latter.  It may be provided as an option for users to select as needed.

**Comment by elanv** [comment]
I have a question about the update policy. If you look at the code in the link below, the validator webhook forbids spec updates, and it seems that some spec updates are required to implement this feature. Are you planning to change the policy to ban updates?

https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/2a5e97e3d38ffce8c1e30ac9eb1699cc85ae9a58/api/v1alpha1/flinkcluster_validate.go#L26

And #61 seems to be related to this feature. if the development roadmap is shared or if assignees for issues are displayed, it will help our project plan and operator contribution plan.

Thank you!

**Comment by functicons** [comment]
Update CR is temporarily forbidden, we want to support updating image and job as you proposed. We also want to support cancel job with savepoint, I just filed #79.

**Comment by functicons** [comment]
Filed #84 which is needed to support seamless job update.

**Comment by elanv** [comment]
Detailed feature request #183
