### ISSUE TITLE
Options to handle cluster when job is finished.

### ISSUE THREAD

**Issue by elanv** [GoogleCloudPlatform/flink-on-k8s-operator#66]
It would be nice to be given the option to handle the flink cluster when the job finishes. Three options will be possible.

1. Delete entire cluster
If the cluster is no longer needed after the job finishes.

2. Leave only jobmanager
If you want to leave only the job manager for checking the dashboard after the job is finished. If all logs are being collected in a separate repository, only the job manager may be left to check the dashboard.

3. Leave the entire cluster
If you want to apply the task-local recovery feature when replaying a job or restarting a failed job, you need to preserve the cluster.
And you may want to preserve the cluster to check the running environment and logs for debugging purposes.

**Comment by functicons** [comment]
For option 3, we usually want it only when job fails, so we might want to set policy differently for job failure and success. Maybe introduce 2 properties in JobSpec:

1. ifJobSucceeds: enum(deleteEntireCluster, deleteTaskManagers, keepEntireCluster), the default is deleteEntireCluster
2. ifJobFails: enum is the same as above, but the default is keepEntireCluster.

What do you think?

**Comment by elanv** [comment]
Looks like a better policy. Thanks for the good suggestion!
